FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Powerline

Powerline is the powerhouse API that runs Meep. It's build on NodeJS and supports any frontend that can make Get, Post and Put requests.
## Login [/login]

### Login [POST]

+ Response 200 (application/json)

        [
            {
                "email": "example@gmail.com",
                "password": "yourpassword"
            }
        ]

## Signup [/signup]

### Login [POST]

+ Response 200 (application/json)

        [
            {
                "email": "example@gmail.com",
                "password": "yourpassword"
            }
        ]


## Logout [/logout]

### Logout [GET]

+ Response 200 (application/json)

